//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagerBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PagerBuddy.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy.
        /// </summary>
        public static string AboutPage_App_Name {
            get {
                return ResourceManager.GetString("AboutPage_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0} ({1}).
        /// </summary>
        public static string AboutPage_App_VersionInfo {
            get {
                return ResourceManager.GetString("AboutPage_App_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy Privacy Policy.
        /// </summary>
        public static string AboutPage_AppPP_Link {
            get {
                return ResourceManager.GetString("AboutPage_AppPP_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Max Bartunik.
        /// </summary>
        public static string AboutPage_Developer {
            get {
                return ResourceManager.GetString("AboutPage_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Permissions.
        /// </summary>
        public static string AboutPage_DeveloperMode_CheckPermissions {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_CheckPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Data.
        /// </summary>
        public static string AboutPage_DeveloperMode_ClearData {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Developer Mode.
        /// </summary>
        public static string AboutPage_DeveloperMode_HideDeveloperModeBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_HideDeveloperModeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log could not be read from file..
        /// </summary>
        public static string AboutPage_DeveloperMode_Log_Default {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_Log_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Client.
        /// </summary>
        public static string AboutPage_DeveloperMode_RestartClientBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_RestartClientBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Log.
        /// </summary>
        public static string AboutPage_DeveloperMode_ShareLogBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_ShareLogBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Alert Page.
        /// </summary>
        public static string AboutPage_DeveloperMode_ShowAlertPageBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_ShowAlertPageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test FCM Message.
        /// </summary>
        public static string AboutPage_DeveloperMode_TestFCMMessageBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_TestFCMMessageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST NOTIFICATION.
        /// </summary>
        public static string AboutPage_DeveloperMode_TestNotification_Message {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_TestNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Test.
        /// </summary>
        public static string AboutPage_DeveloperMode_TestNotificationBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_TestNotificationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level: {0}.
        /// </summary>
        public static string AboutPage_LogLevel_Prefix {
            get {
                return ResourceManager.GetString("AboutPage_LogLevel_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Personal Information you enter while using this App is stored locally on your device. Only necessary information for authentication is passed to Telegram. If an error occurs some log data regarding device statistics and configuration of PagerBuddy may be collected. Links to Telegrams Privacy Policy and the Privacy Policy for PagerBuddy are provided below..
        /// </summary>
        public static string AboutPage_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AboutPage_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy is neither affiliated to nor endorsed by Telegram..
        /// </summary>
        public static string AboutPage_Telegram {
            get {
                return ResourceManager.GetString("AboutPage_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Privacy Policy.
        /// </summary>
        public static string AboutPage_TelegramPP_Link {
            get {
                return ResourceManager.GetString("AboutPage_TelegramPP_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ActiveTimePopup_Cancel {
            get {
                return ResourceManager.GetString("ActiveTimePopup_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ActiveTimePopup_Confirm {
            get {
                return ResourceManager.GetString("ActiveTimePopup_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string ActiveTimePopup_DayFriday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string ActiveTimePopup_DayMonday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string ActiveTimePopup_DaySaturday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string ActiveTimePopup_DaySunday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string ActiveTimePopup_DayThursday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string ActiveTimePopup_DayTuesday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string ActiveTimePopup_DayWednesday {
            get {
                return ResourceManager.GetString("ActiveTimePopup_DayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST ALERT.
        /// </summary>
        public static string Alert_TestFilter {
            get {
                return ResourceManager.GetString("Alert_TestFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event was not triggered yet.
        /// </summary>
        public static string AlertStatus_Status_Default {
            get {
                return ResourceManager.GetString("AlertStatus_Status_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chat.
        /// </summary>
        public static string Android_AndroidNotifications_Action_Telegram {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_Action_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert notifications you configured in PagerBuddy..
        /// </summary>
        public static string Android_AndroidNotifications_AlertChannel_Description {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_AlertChannel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Notifications.
        /// </summary>
        public static string Android_AndroidNotifications_AlertChannel_Title {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_AlertChannel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications relevant to general app behaviour and updates..
        /// </summary>
        public static string Android_AndroidNotifications_StandardChannel_Description {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_StandardChannel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Information.
        /// </summary>
        public static string Android_AndroidNotifications_StandardChannel_Title {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_StandardChannel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagerbuddy@bartunik.de.
        /// </summary>
        public static string App_DeveloperContact {
            get {
                return ResourceManager.GetString("App_DeveloperContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST NOTIFICATION.
        /// </summary>
        public static string App_DeveloperMode_AlertPage_Message {
            get {
                return ResourceManager.GetString("App_DeveloperMode_AlertPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Alert Chat Title.
        /// </summary>
        public static string App_DeveloperMode_AlertPage_Title {
            get {
                return ResourceManager.GetString("App_DeveloperMode_AlertPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out PagerBuddy and never miss an urgent message again. The app is currently available for Android and will be coming soon for iOS..
        /// </summary>
        public static string App_Share_Message {
            get {
                return ResourceManager.GetString("App_Share_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you have no active chats in Telegram. First join a group or start a chat in Telegram to add it as an alert trigger..
        /// </summary>
        public static string ConfigureGroupPage_Warning_NoChats {
            get {
                return ResourceManager.GetString("ConfigureGroupPage_Warning_NoChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string HomeStatusPage_DNDPermissionPrompt_Cancel {
            get {
                return ResourceManager.GetString("HomeStatusPage_DNDPermissionPrompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take me there.
        /// </summary>
        public static string HomeStatusPage_DNDPermissionPrompt_Confirm {
            get {
                return ResourceManager.GetString("HomeStatusPage_DNDPermissionPrompt_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure notifications when the phone is set to silent or Do Not Disturb please grant PagerBuddy access in your permissions settings..
        /// </summary>
        public static string HomeStatusPage_DNDPermissionPrompt_Message {
            get {
                return ResourceManager.GetString("HomeStatusPage_DNDPermissionPrompt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Do Not Disturb access.
        /// </summary>
        public static string HomeStatusPage_DNDPermissionPrompt_Title {
            get {
                return ResourceManager.GetString("HomeStatusPage_DNDPermissionPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start using PagerBuddy by logging in to your Telegram account..
        /// </summary>
        public static string HomeStatusPage_Error_NoTelegram {
            get {
                return ResourceManager.GetString("HomeStatusPage_Error_NoTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Except.
        /// </summary>
        public static string HomeStatusPage_FlipTime_Prefix {
            get {
                return ResourceManager.GetString("HomeStatusPage_FlipTime_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HomeStatusPage_Snooze_Cancel {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        public static string HomeStatusPage_Snooze_Day {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days.
        /// </summary>
        public static string HomeStatusPage_Snooze_Days {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hours.
        /// </summary>
        public static string HomeStatusPage_Snooze_Hours {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string HomeStatusPage_Snooze_Month {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate all alerts for.
        /// </summary>
        public static string HomeStatusPage_Snooze_Prompt {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        public static string HomeStatusPage_Snooze_Week {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Weeks.
        /// </summary>
        public static string HomeStatusPage_Snooze_Weeks {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy.
        /// </summary>
        public static string HomeStatusPage_Title {
            get {
                return ResourceManager.GetString("HomeStatusPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts deactivated.
        /// </summary>
        public static string HomeStatusPage_Warning_Deactivated {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PagerBuddy alert groups found. Make sure you have been added to a Telegram alert group using PagerBuddy..
        /// </summary>
        public static string HomeStatusPage_Warning_EmptyList {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts deactivated untill\n{0:dd.MM.yy HH:mm}.
        /// </summary>
        public static string HomeStatusPage_Warning_Snooze {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        public static string HomeStatusPage_WelcomePrompt_Cancel {
            get {
                return ResourceManager.GetString("HomeStatusPage_WelcomePrompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string HomeStatusPage_WelcomePrompt_Confirm {
            get {
                return ResourceManager.GetString("HomeStatusPage_WelcomePrompt_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! I am your notification Buddy for urgent messages. Start by logging in to your Telegram account..
        /// </summary>
        public static string HomeStatusPage_WelcomePrompt_Message {
            get {
                return ResourceManager.GetString("HomeStatusPage_WelcomePrompt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Login.
        /// </summary>
        public static string HomeStatusPage_WelcomePrompt_Title {
            get {
                return ResourceManager.GetString("HomeStatusPage_WelcomePrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string LoginCodePage_Code_Placeholder {
            get {
                return ResourceManager.GetString("LoginCodePage_Code_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        public static string LoginCodePage_Error_Default {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code was not correct!.
        /// </summary>
        public static string LoginCodePage_Error_InvalidCode {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code is not valid. Telegram authentication codes consist of five numbers..
        /// </summary>
        public static string LoginCodePage_Error_NoCode {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_NoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Telegram. Check your internet connection and try again..
        /// </summary>
        public static string LoginCodePage_Error_Offline {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string LoginCodePage_NextBtn {
            get {
                return ResourceManager.GetString("LoginCodePage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate using the confirmation code sent to your phone number via Telegram/SMS.
        /// </summary>
        public static string LoginCodePage_Prompt {
            get {
                return ResourceManager.GetString("LoginCodePage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string LoginCodePage_Title {
            get {
                return ResourceManager.GetString("LoginCodePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        public static string LoginPasswordPage_Error_Default {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        public static string LoginPasswordPage_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Telegram. Check your internet connection and try again..
        /// </summary>
        public static string LoginPasswordPage_Error_Offline {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Error_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPasswordPage_NextBtn {
            get {
                return ResourceManager.GetString("LoginPasswordPage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPasswordPage_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password for your Telegram account.
        /// </summary>
        public static string LoginPasswordPage_Prompt {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string LoginPasswordPage_Title {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        public static string LoginPhonePage_Error_Default {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not associated to a telegram account or too many login attempts have been made. Check the phone number you entered..
        /// </summary>
        public static string LoginPhonePage_Error_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered number is not a valid phone number. Check your input and use a country code..
        /// </summary>
        public static string LoginPhonePage_Error_NoPhoneNumber {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_NoPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Telegram. Check your internet connection and try again..
        /// </summary>
        public static string LoginPhonePage_Error_Offline {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Telegram App.
        /// </summary>
        public static string LoginPhonePage_InstallTelegram {
            get {
                return ResourceManager.GetString("LoginPhonePage_InstallTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string LoginPhonePage_NextBtn {
            get {
                return ResourceManager.GetString("LoginPhonePage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to log into your Telegram account. If you do not have Telegram yet, install the app and setup a new account for free..
        /// </summary>
        public static string LoginPhonePage_Prompt {
            get {
                return ResourceManager.GetString("LoginPhonePage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPhonePage_Title {
            get {
                return ResourceManager.GetString("LoginPhonePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuPage_Action_About {
            get {
                return ResourceManager.GetString("MenuPage_Action_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuPage_Action_Logout {
            get {
                return ResourceManager.GetString("MenuPage_Action_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        public static string MenuPage_Action_NotificationSettings {
            get {
                return ResourceManager.GetString("MenuPage_Action_NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string MenuPage_Action_Share {
            get {
                return ResourceManager.GetString("MenuPage_Action_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support PagerBuddy.
        /// </summary>
        public static string MenuPage_Action_Website {
            get {
                return ResourceManager.GetString("MenuPage_Action_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MenuPage_LogoutPrompt_Cancel {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MenuPage_LogoutPrompt_Confirm {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All configurations will be deleted..
        /// </summary>
        public static string MenuPage_LogoutPrompt_Text {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuPage_LogoutPrompt_Title {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MenuPage_UserName_Default {
            get {
                return ResourceManager.GetString("MenuPage_UserName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string MenuPage_UserPhone_Default {
            get {
                return ResourceManager.GetString("MenuPage_UserPhone_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy was updated to the newest version. Some major changes have been made to how the app works and your settings could not be retained. Head to the app now and reconfigure your settings..
        /// </summary>
        public static string Notification_BreakingUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_BreakingUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy updated.
        /// </summary>
        public static string Notification_BreakingUpdate_Title {
            get {
                return ResourceManager.GetString("Notification_BreakingUpdate_Title", resourceCulture);
            }
        }
    }
}
