//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmManagerT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmManagerT.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All configured alerts are removed on logout..
        /// </summary>
        internal static string AccountPage_Logout_Warning {
            get {
                return ResourceManager.GetString("AccountPage_Logout_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string AccountPage_LogoutBtn {
            get {
                return ResourceManager.GetString("AccountPage_LogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountPage_Title {
            get {
                return ResourceManager.GetString("AccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string AccountPage_UserName_Default {
            get {
                return ResourceManager.GetString("AccountPage_UserName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string AccountPage_UserPhone_Default {
            get {
                return ResourceManager.GetString("AccountPage_UserPhone_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated untill {0:dd.MM.yy HH:mm}.
        /// </summary>
        internal static string AlertStatus_Status_Deactivated {
            get {
                return ResourceManager.GetString("AlertStatus_Status_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event was not triggered yet.
        /// </summary>
        internal static string AlertStatus_Status_Default {
            get {
                return ResourceManager.GetString("AlertStatus_Status_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Chat.
        /// </summary>
        internal static string ConfigureGroupPage_Title {
            get {
                return ResourceManager.GetString("ConfigureGroupPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string ConfigureKeywordPage_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ConfigureKeywordPage_NextBtn {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allways.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Any {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Friday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Monday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Saturday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Sunday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Thursday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Tuesday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Day_Wednesday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Set {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ConfigureKeywordPage_Time_Title {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Configuration.
        /// </summary>
        internal static string ConfigureKeywordPage_Title {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any message.
        /// </summary>
        internal static string ConfigureKeywordPage_Trigger_Any {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages with a keyword.
        /// </summary>
        internal static string ConfigureKeywordPage_Trigger_Keyword {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expression.
        /// </summary>
        internal static string ConfigureKeywordPage_Trigger_RegEx {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages from AlarmManagerT-Server.
        /// </summary>
        internal static string ConfigureKeywordPage_Trigger_Server {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string ConfigureKeywordPage_Trigger_Title {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        internal static string HomeStatusPage_Error_NoInternet {
            get {
                return ResourceManager.GetString("HomeStatusPage_Error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to Telegram.
        /// </summary>
        internal static string HomeStatusPage_Error_NoTelegram {
            get {
                return ResourceManager.GetString("HomeStatusPage_Error_NoTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate for.
        /// </summary>
        internal static string HomeStatusPage_IndividualSnooze_Prompt {
            get {
                return ResourceManager.GetString("HomeStatusPage_IndividualSnooze_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Cancel {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Day {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Days {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hours.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Hours {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Month {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate all alerts for.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Prompt {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Week {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Weeks.
        /// </summary>
        internal static string HomeStatusPage_Snooze_Weeks {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlarmManagerT.
        /// </summary>
        internal static string HomeStatusPage_Title {
            get {
                return ResourceManager.GetString("HomeStatusPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts deactivated.
        /// </summary>
        internal static string HomeStatusPage_Warning_Deactivated {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts deactivated untill {0:dd.MM.yy HH:mm}.
        /// </summary>
        internal static string HomeStatusPage_Warning_Snooze {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string LoginCodePage_Code_Placeholder {
            get {
                return ResourceManager.GetString("LoginCodePage_Code_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        internal static string LoginCodePage_Error_Default {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string LoginCodePage_NextBtn {
            get {
                return ResourceManager.GetString("LoginCodePage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate using the confirmation code sent to your phone number.
        /// </summary>
        internal static string LoginCodePage_Prompt {
            get {
                return ResourceManager.GetString("LoginCodePage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginCodePage_Title {
            get {
                return ResourceManager.GetString("LoginCodePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        internal static string LoginPhonePage_Error_Default {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not associated to a telegram account or too many login attempts have been made. Check the phone number you entered..
        /// </summary>
        internal static string LoginPhonePage_Error_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPhonePage_NextBtn {
            get {
                return ResourceManager.GetString("LoginPhonePage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +49.
        /// </summary>
        internal static string LoginPhonePage_PhoneNumber_Placeholder {
            get {
                return ResourceManager.GetString("LoginPhonePage_PhoneNumber_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to log into your Telegram account:.
        /// </summary>
        internal static string LoginPhonePage_Prompt {
            get {
                return ResourceManager.GetString("LoginPhonePage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPhonePage_Title {
            get {
                return ResourceManager.GetString("LoginPhonePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuPage_Action_About {
            get {
                return ResourceManager.GetString("MenuPage_Action_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string MenuPage_Action_NotificationSettings {
            get {
                return ResourceManager.GetString("MenuPage_Action_NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string MenuPage_Action_Share {
            get {
                return ResourceManager.GetString("MenuPage_Action_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string MenuPage_UserName_Default {
            get {
                return ResourceManager.GetString("MenuPage_UserName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string MenuPage_UserPhone_Default {
            get {
                return ResourceManager.GetString("MenuPage_UserPhone_Default", resourceCulture);
            }
        }
    }
}
