//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmManagerT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmManagerT.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy.
        /// </summary>
        public static string AboutPage_App_Name {
            get {
                return ResourceManager.GetString("AboutPage_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0} ({1}).
        /// </summary>
        public static string AboutPage_App_VersionInfo {
            get {
                return ResourceManager.GetString("AboutPage_App_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Developer Mode.
        /// </summary>
        public static string AboutPage_DeveloperMode_HideDeveloperModeBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_HideDeveloperModeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log could not be read from file..
        /// </summary>
        public static string AboutPage_DeveloperMode_Log_Default {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_Log_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Client.
        /// </summary>
        public static string AboutPage_DeveloperMode_RestartClientBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_RestartClientBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Log.
        /// </summary>
        public static string AboutPage_DeveloperMode_ShareLogBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_ShareLogBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Alert Page.
        /// </summary>
        public static string AboutPage_DeveloperMode_ShowAlertPageBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_ShowAlertPageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test FCM Message.
        /// </summary>
        public static string AboutPage_DeveloperMode_TestFCMMessageBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_TestFCMMessageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST NOTIFICATION.
        /// </summary>
        public static string AboutPage_DeveloperMode_TestNotification_Message {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_TestNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Notification.
        /// </summary>
        public static string AboutPage_DeveloperMode_TestNotificationBtn {
            get {
                return ResourceManager.GetString("AboutPage_DeveloperMode_TestNotificationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated untill {0:dd.MM.yy HH:mm}.
        /// </summary>
        public static string AlertStatus_Status_Deactivated {
            get {
                return ResourceManager.GetString("AlertStatus_Status_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event was not triggered yet.
        /// </summary>
        public static string AlertStatus_Status_Default {
            get {
                return ResourceManager.GetString("AlertStatus_Status_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any chat message.
        /// </summary>
        public static string AlertStatus_Trigger_Any {
            get {
                return ResourceManager.GetString("AlertStatus_Trigger_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy-Server.
        /// </summary>
        public static string AlertStatus_Trigger_Server {
            get {
                return ResourceManager.GetString("AlertStatus_Trigger_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured alert notifications..
        /// </summary>
        public static string Android_AndroidNotifications_AlertChannel_Description {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_AlertChannel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Notifications.
        /// </summary>
        public static string Android_AndroidNotifications_AlertChannel_Title {
            get {
                return ResourceManager.GetString("Android_AndroidNotifications_AlertChannel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST NOTIFICATION.
        /// </summary>
        public static string App_DeveloperMode_AlertPage_Message {
            get {
                return ResourceManager.GetString("App_DeveloperMode_AlertPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Alert Group Title.
        /// </summary>
        public static string App_DeveloperMode_AlertPage_Title {
            get {
                return ResourceManager.GetString("App_DeveloperMode_AlertPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out PagerBuddy and never miss an urgent message again. The app is available for Android and iOS..
        /// </summary>
        public static string App_Share_Message {
            get {
                return ResourceManager.GetString("App_Share_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Chat.
        /// </summary>
        public static string ConfigureGroupPage_Title {
            get {
                return ResourceManager.GetString("ConfigureGroupPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use regular expressions.
        /// </summary>
        public static string ConfigureKeywordPage_Keyword_Hint {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Keyword_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string ConfigureKeywordPage_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConfigureKeywordPage_NextBtn {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allways.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Any {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Friday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Monday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Saturday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Sunday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Thursday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Tuesday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Day_Wednesday {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Day_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string ConfigureKeywordPage_Time_From {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Set {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ConfigureKeywordPage_Time_Title {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string ConfigureKeywordPage_Time_To {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Time_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Configuration.
        /// </summary>
        public static string ConfigureKeywordPage_Title {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any message.
        /// </summary>
        public static string ConfigureKeywordPage_Trigger_Any {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages with a keyword.
        /// </summary>
        public static string ConfigureKeywordPage_Trigger_Keyword {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages from PagerBuddy-Server.
        /// </summary>
        public static string ConfigureKeywordPage_Trigger_Server {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string ConfigureKeywordPage_Trigger_Title {
            get {
                return ResourceManager.GetString("ConfigureKeywordPage_Trigger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take me there.
        /// </summary>
        public static string HomeStatusPage_DND_PermissionPrompt_Confirm {
            get {
                return ResourceManager.GetString("HomeStatusPage_DND_PermissionPrompt_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure notifications when the phone is set to silent or Do Not Disturb please grant PagerBuddy access in your permissions settings..
        /// </summary>
        public static string HomeStatusPage_DNDPermissionPrompt_Message {
            get {
                return ResourceManager.GetString("HomeStatusPage_DNDPermissionPrompt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Do Not Disturb access.
        /// </summary>
        public static string HomeStatusPage_DNDPermissionPrompt_Title {
            get {
                return ResourceManager.GetString("HomeStatusPage_DNDPermissionPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string HomeStatusPage_Error_NoInternet {
            get {
                return ResourceManager.GetString("HomeStatusPage_Error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to Telegram.
        /// </summary>
        public static string HomeStatusPage_Error_NoTelegram {
            get {
                return ResourceManager.GetString("HomeStatusPage_Error_NoTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate for.
        /// </summary>
        public static string HomeStatusPage_IndividualSnooze_Prompt {
            get {
                return ResourceManager.GetString("HomeStatusPage_IndividualSnooze_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string HomeStatusPage_Snooze_Cancel {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        public static string HomeStatusPage_Snooze_Day {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days.
        /// </summary>
        public static string HomeStatusPage_Snooze_Days {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hours.
        /// </summary>
        public static string HomeStatusPage_Snooze_Hours {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string HomeStatusPage_Snooze_Month {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate all alerts for.
        /// </summary>
        public static string HomeStatusPage_Snooze_Prompt {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        public static string HomeStatusPage_Snooze_Week {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Weeks.
        /// </summary>
        public static string HomeStatusPage_Snooze_Weeks {
            get {
                return ResourceManager.GetString("HomeStatusPage_Snooze_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagerBuddy.
        /// </summary>
        public static string HomeStatusPage_Title {
            get {
                return ResourceManager.GetString("HomeStatusPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts deactivated.
        /// </summary>
        public static string HomeStatusPage_Warning_Deactivated {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts deactivated untill {0:dd.MM.yy HH:mm}.
        /// </summary>
        public static string HomeStatusPage_Warning_Snooze {
            get {
                return ResourceManager.GetString("HomeStatusPage_Warning_Snooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string LoginCodePage_Code_Placeholder {
            get {
                return ResourceManager.GetString("LoginCodePage_Code_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        public static string LoginCodePage_Error_Default {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code was not correct!.
        /// </summary>
        public static string LoginCodePage_Error_InvalidCode {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code is not valid. Telegram authentication codes consist of five numbers..
        /// </summary>
        public static string LoginCodePage_Error_NoCode {
            get {
                return ResourceManager.GetString("LoginCodePage_Error_NoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string LoginCodePage_NextBtn {
            get {
                return ResourceManager.GetString("LoginCodePage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate using the confirmation code sent to your phone number.
        /// </summary>
        public static string LoginCodePage_Prompt {
            get {
                return ResourceManager.GetString("LoginCodePage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string LoginCodePage_Title {
            get {
                return ResourceManager.GetString("LoginCodePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        public static string LoginPasswordPage_Error_Default {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        public static string LoginPasswordPage_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPasswordPage_NextBtn {
            get {
                return ResourceManager.GetString("LoginPasswordPage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPasswordPage_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password for your Telegram account:.
        /// </summary>
        public static string LoginPasswordPage_Prompt {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string LoginPasswordPage_Title {
            get {
                return ResourceManager.GetString("LoginPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured. Try again later....
        /// </summary>
        public static string LoginPhonePage_Error_Default {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not associated to a telegram account or too many login attempts have been made. Check the phone number you entered..
        /// </summary>
        public static string LoginPhonePage_Error_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered number is not a valid phone number. Check your input and use a country code..
        /// </summary>
        public static string LoginPhonePage_Error_NoPhoneNumber {
            get {
                return ResourceManager.GetString("LoginPhonePage_Error_NoPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPhonePage_NextBtn {
            get {
                return ResourceManager.GetString("LoginPhonePage_NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to log into your Telegram account:.
        /// </summary>
        public static string LoginPhonePage_Prompt {
            get {
                return ResourceManager.GetString("LoginPhonePage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPhonePage_Title {
            get {
                return ResourceManager.GetString("LoginPhonePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuPage_Action_About {
            get {
                return ResourceManager.GetString("MenuPage_Action_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuPage_Action_Logout {
            get {
                return ResourceManager.GetString("MenuPage_Action_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        public static string MenuPage_Action_NotificationSettings {
            get {
                return ResourceManager.GetString("MenuPage_Action_NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string MenuPage_Action_Share {
            get {
                return ResourceManager.GetString("MenuPage_Action_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MenuPage_LogoutPrompt_Cancel {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MenuPage_LogoutPrompt_Confirm {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All configurations will be deleted..
        /// </summary>
        public static string MenuPage_LogoutPrompt_Text {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuPage_LogoutPrompt_Title {
            get {
                return ResourceManager.GetString("MenuPage_LogoutPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MenuPage_UserName_Default {
            get {
                return ResourceManager.GetString("MenuPage_UserName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string MenuPage_UserPhone_Default {
            get {
                return ResourceManager.GetString("MenuPage_UserPhone_Default", resourceCulture);
            }
        }
    }
}
